"""first revision

迁移 ID: 4c126bfc6e19
父迁移: 
创建时间: 2026-04-06 09:04:36.713170

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4c126bfc6e19'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ('nonebot_plugin_vortex_lexicon',)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nonebot_plugin_vortex_lexicon_lexicon', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'permission',
                sa.String(length=32),
                nullable=False,
                server_default=sa.text("'all'"),
            )
        )
        batch_op.add_column(
            sa.Column(
                'allow_users',
                sa.String(length=2000),
                nullable=False,
                server_default=sa.text("''"),
            )
        )

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nonebot_plugin_vortex_lexicon_lexicon', schema=None) as batch_op:
        batch_op.drop_column('allow_users')
        batch_op.drop_column('permission')

    # ### end Alembic commands ###
